enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

app-name = "Google News"
build-mode = "both"
patches-source = "https://github.com/hoo-dles/morphe-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
arch = "arm64"

